export const dalhousieUniversity = {
  name: 'Dalhousie University',
  departments: [
    {
      name: 'Faculty of Computer Science',
      classes: [
        { code: 'CSCI 1105', name: 'Introduction to Programming' },
        { code: 'CSCI 1110', name: 'Introduction to Computer Science' },
        { code: 'CSCI 1120', name: 'Introduction to Computer Systems' },
        { code: 'CSCI 1170', name: 'Introduction to Web Design and Development' },
        { code: 'CSCI 1800', name: 'Society and Technology' },
        { code: 'CSCI 1801', name: 'Case Studies in Computing and Society' },
        { code: 'CSCI 2100', name: 'Communication Skills' },
        { code: 'CSCI 2110', name: 'Data Structures and Algorithms' },
        { code: 'CSCI 2112', name: 'Discrete Structures I' },
        { code: 'CSCI 2121', name: 'Computer Organization with Assembly Language' },
        { code: 'CSCI 2134', name: 'Software Development' },
        { code: 'CSCI 2141', name: 'Introduction to Database Systems' },
        { code: 'CSCI 2170', name: 'Introduction to Server Side Scripting' },
        { code: 'CSCI 3101', name: 'Social, Ethical and Professional Issues in Computer Science' },
        { code: 'CSCI 3110', name: 'Design and Analysis of Algorithms I' },
        { code: 'CSCI 3120', name: 'Operating Systems' },
        { code: 'CSCI 3130', name: 'Introduction to Software Engineering' },
        { code: 'CSCI 3136', name: 'Principles of Programming Languages' },
        { code: 'CSCI 3151', name: 'Web Intelligence' },
        { code: 'CSCI 3154', name: 'AI and Games' },
        { code: 'CSCI 3160', name: 'User Interface Design' },
        { code: 'CSCI 3171', name: 'Network Computing' },
        { code: 'CSCI 3172', name: 'Web-Centric Computing' },
        { code: 'CSCI 3190', name: 'Community Outreach' },
        { code: 'CSCI 4115', name: 'Topics in Algorithms' },
        { code: 'CSCI 4116', name: 'Cryptography' },
        { code: 'CSCI 4117', name: 'Advanced Data Structures' },
        { code: 'CSCI 4125', name: 'High Performance Computing' },
        { code: 'CSCI 4140', name: 'Advanced Database Systems' },
        { code: 'CSCI 4141', name: 'Information Retrieval' },
        { code: 'CSCI 4144', name: 'Introduction to Data Mining and Data Warehousing' },
        { code: 'CSCI 4145', name: 'Cloud Computing' },
        { code: 'CSCI 4150', name: 'Introduction to Artificial Intelligence' },
        { code: 'CSCI 4152', name: 'Natural Language Processing' },
        { code: 'CSCI 4155', name: 'Machine Learning' },
        { code: 'CSCI 4160', name: 'Computer Graphics' },
        { code: 'CSCI 4163', name: 'Human-Computer Interaction' },
        { code: 'CSCI 4166', name: 'Visualization' },
        { code: 'CSCI 4168', name: 'Game Design and Development' },
        { code: 'CSCI 4169', name: 'Technology Innovation' },
        { code: 'CSCI 4171', name: 'Networks and Communications' },
        { code: 'CSCI 4174', name: 'Network Security' },
        { code: 'CSCI 4176', name: 'Mobile Computing' },
        { code: 'CSCI 4177', name: 'Advanced Web Services' },
        { code: 'CSCI 4180', name: 'Introduction to Computational Biology and Bioinformatics' },
        { code: 'CSCI 4190', name: 'Special Topics in Computer Science' },
        { code: 'CSCI 4192', name: 'Directed Studies' },
        { code: 'CSCI 4193', name: 'Technology Innovation' },
      ],
    },
    {
      name: 'Faculty of Science',
      classes: [
        // Biology
        { code: 'BIOL 1010', name: 'Principles of Biology' },
        { code: 'BIOL 1020', name: 'Introductory Biology I: Cells, Genetics & Evolution' },
        { code: 'BIOL 1021', name: 'Introductory Biology II: Organismal Biology & Ecology' },
        { code: 'BIOL 2003', name: 'Animal Diversity' },
        { code: 'BIOL 2004', name: 'Diversity of Plants and Microorganisms' },
        { code: 'BIOL 2020', name: 'Cell Biology' },
        { code: 'BIOL 2030', name: 'Genetics and Molecular Biology' },
        { code: 'BIOL 2040', name: 'Evolution' },
        { code: 'BIOL 2060', name: 'Introductory Ecology' },
        // Chemistry
        { code: 'CHEM 1011', name: 'Concepts in Chemistry: Structure and Reactivity' },
        { code: 'CHEM 1012', name: 'Concepts in Chemistry: Energy and Equilibrium' },
        { code: 'CHEM 2101', name: 'Introductory Inorganic Chemistry' },
        { code: 'CHEM 2201', name: 'Introductory Analytical Chemistry' },
        { code: 'CHEM 2301', name: 'Introduction to Physical Chemistry I' },
        { code: 'CHEM 2401', name: 'Organic Chemistry I' },
        // Physics
        { code: 'PHYC 1190', name: 'Introduction to Physics' },
        { code: 'PHYC 1290', name: 'Introduction to Physics' },
        { code: 'PHYC 1300', name: 'Physics In and Around You' },
        { code: 'PHYC 2140', name: 'Physics Tools: Theory' },
        { code: 'PHYC 2150', name: 'Physics Tools: Experiment' },
        { code: 'PHYC 2510', name: 'Electricity and Magnetism' },
        { code: 'PHYC 2515', name: 'Modern Physics' },
        // Mathematics
        { code: 'MATH 1000', name: 'Differential and Integral Calculus I' },
        { code: 'MATH 1010', name: 'Differential and Integral Calculus II' },
        { code: 'MATH 1030', name: 'Matrix Theory and Linear Algebra I' },
        { code: 'MATH 2001', name: 'Intermediate Calculus I' },
        { code: 'MATH 2002', name: 'Intermediate Calculus II' },
        { code: 'MATH 2030', name: 'Matrix Theory and Linear Algebra II' },
        // Statistics
        { code: 'STAT 1060', name: 'Introductory Statistics for Science and Health Sciences' },
        { code: 'STAT 2060', name: 'Introduction to Probability and Statistics' },
        { code: 'STAT 2080', name: 'Statistical Methods for Data Analysis and Inference' },
      ],
    },
    {
      name: 'Faculty of Arts and Social Sciences',
      classes: [
        // History
        { code: 'HIST 1020', name: 'Introduction to European History' },
        { code: 'HIST 1510', name: 'The Globalization of European Society, 1400-1800' },
        {
          code: 'HIST 1701',
          name: 'History of the Americas: From Pre-Contact to the Revolutionary Era',
        },
        { code: 'HIST 2205', name: 'Historical Issues in Indigenous Studies' },
        { code: 'HIST 2211', name: 'Social History of Canada before 1870' },
        // English
        { code: 'ENGL 1000', name: 'Introduction to Literature' },
        { code: 'ENGL 1040', name: 'Reading Popular Culture' },
        { code: 'ENGL 1100', name: 'Writing for University' },
        { code: 'ENGL 2001', name: 'British Literature to 1800' },
        { code: 'ENGL 2002', name: 'British Literature after 1800' },
        // Philosophy
        { code: 'PHIL 1000', name: 'Introduction to Philosophy' },
        { code: 'PHIL 1010', name: 'Life, Death, and Contemporary Issues' },
        { code: 'PHIL 2130', name: 'Logic: Deduction' },
        { code: 'PHIL 2160', name: 'Philosophical Issues of Feminism' },
        { code: 'PHIL 2170', name: 'Philosophy of Sex and Love' },
        // Sociology and Social Anthropology
        { code: 'SOSA 1000', name: 'Introduction to Sociology and Social Anthropology' },
        { code: 'SOSA 1002', name: 'People and Culture' },
        { code: 'SOSA 1003', name: 'Introduction to Sociology' },
        { code: 'SOSA 2001', name: 'Ethnography in a Global Context' },
        { code: 'SOSA 2002', name: 'The Sociological Perspective: Thinking and Doing Sociology' },
        // Political Science
        { code: 'POLI 1050', name: 'Introduction to Government and Politics' },
        { code: 'POLI 1100', name: 'Political Worlds: Themes and Concepts' },
        { code: 'POLI 1500', name: 'Global Politics' },
        {
          code: 'POLI 2210',
          name: 'Unity and Diversity: The Federal Dynamics of Canadian Politics',
        },
        {
          code: 'POLI 2220',
          name: 'Political Power and Partisan Politics: The Structures of Canadian Parliamentary Government',
        },
      ],
    },
    {
      name: 'Faculty of Management',
      classes: [
        { code: 'COMM 1010', name: 'Business in a Global Context' },
        { code: 'COMM 1101', name: 'Introductory Accounting I' },
        { code: 'COMM 1102', name: 'Introductory Accounting II' },
        { code: 'COMM 1502', name: 'Core Business Applications' },
        { code: 'COMM 1710', name: 'Business Communications I' },
        { code: 'COMM 1720', name: 'Business Communications II' },
        { code: 'COMM 2202', name: 'Finance I' },
        { code: 'COMM 2203', name: 'Finance II' },
        { code: 'COMM 2301', name: 'Organizational Behaviour' },
        { code: 'COMM 2303', name: 'Introduction to Managing People' },
        { code: 'COMM 2401', name: 'Introduction to Marketing' },
        { code: 'COMM 2501', name: 'Statistics for Business I' },
        { code: 'COMM 2502', name: 'Predictive Analytics' },
        { code: 'COMM 2603', name: 'Legal Aspects of Business' },
        { code: 'COMM 3101', name: 'Information Systems' },
        { code: 'COMM 3511', name: 'Management Information Systems' },
        { code: 'COMM 4351', name: 'Competitive Strategy' },
        { code: 'COMM 4352', name: 'Strategic Management' },
        { code: 'MGMT 1000', name: 'Managing Organizational Issues I' },
        { code: 'MGMT 1001', name: 'Managing Organizational Issues II' },
        { code: 'MGMT 1601', name: 'Electronic Information Management' },
        {
          code: 'MGMT 2303',
          name: 'People, Work, and Organizations: Micro Organizational Behaviour',
        },
        {
          code: 'MGMT 2304',
          name: 'People, Work, and Organizations: Macro Aspects of Organizational Behaviour',
        },
        { code: 'MGMT 2801', name: 'Government Structure' },
        { code: 'MGMT 3201', name: 'Financial Management' },
        { code: 'MGMT 3501', name: 'Operations Management' },
        { code: 'MGMT 3602', name: 'Professional Communications Skills' },
        { code: 'MGMT 3907', name: 'New Venture Creation' },
        { code: 'MGMT 4001', name: 'Strategy Formulation' },
        { code: 'MGMT 4002', name: 'Strategy Implementation' },
      ],
    },
  ],
};

export const universities = [dalhousieUniversity];
